PRODUCT_COPY_FILES += \
    vendor/xiaomi/mi8937/camera/land/vendor/bin/land_mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/land_mm-qcamera-daemon \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/msm8937_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/msm8937_camera.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/ofilm_s5k5e8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/ofilm_s5k5e8_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/ov13853_q13853a_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/ov13853_q13853a_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/plus_ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/plus_ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/qtech_s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/qtech_s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/s5k3l8_f3l8yam_new_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/s5k3l8_f3l8yam_new_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/s5k5e8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/s5k5e8_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/sunny_ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/sunny_ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/sunny_s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/sunny_s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/etc/land_camera/sunny_s5k3l8_f3l8yam_new_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/land_camera/sunny_s5k3l8_f3l8yam_new_chromatix.xml \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCash_pmic.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_c2d_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_cpp_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_dcrf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_dcrf.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_frame_algorithm.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_iface_modules.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_imglib_modules.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_isp_modules.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_is.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_mct.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_mct.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_pp_buf_mgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_pp_buf_mgr.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_pproc_modules.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_q3a_core.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_sensor_modules.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_stats_algorithm.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_stats_modules.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_vpe_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera2_wnr_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_chromaflash_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_chromaflash_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_dbg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_dbg.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_dcrf_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_dcrf_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_dummyalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_dummyalgo.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_eebinparse.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_eebinparse.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_eeprom_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_eeprom_util.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_eztune_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_eztune_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_faceproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_hdr_gb_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_imglib_faceproc_adspstub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_imglib_faceproc_adspstub.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_imglib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_abf40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_abf40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_bcc40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_bcc40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_be_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_be_stats44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_bf_stats47.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_bf_stats47.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_bg_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_bg_stats44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_bhist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_bhist_stats44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_bpc40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_bpc40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_chroma_enhan40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_chroma_enhan40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_chroma_suppress40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_chroma_suppress40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_clamp_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_clamp_encoder40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_clamp_video40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_clamp_video40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_clamp_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_clamp_viewfinder40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_color_correct40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_color_correct40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_color_xform_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_color_xform_encoder40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_color_xform_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_color_xform_viewfinder40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_cs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_cs_stats44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_demosaic40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_demosaic40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_demux40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_demux40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_fovcrop_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_fovcrop_encoder40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_fovcrop_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_fovcrop_viewfinder40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_gamma40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_gamma40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_ihist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_ihist_stats44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_linearization40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_linearization40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_ltm44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_ltm44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_luma_adaptation40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_luma_adaptation40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_mce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_mce40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_mesh_rolloff40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_mesh_rolloff40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_rs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_rs_stats44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_scaler_encoder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_scaler_encoder44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_scaler_viewfinder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_scaler_viewfinder44.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_sce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_sce40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_sub_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_sub_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_template.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_template.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_isp_wb40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_isp_wb40.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_llvd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_llvd.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_optizoom_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_optizoom_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov13850_q13v06k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov13850_q13v06k.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov13850.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov13850.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov13853_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov13853_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov13853_q13853a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov13853_q13853a.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov2685_scv3b4035.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov2685_scv3b4035.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov2685.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov2685.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov4688_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov4688_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov4688.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov4688.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov5645.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov5645.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov5670_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov5670_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov5670.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov5670.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov8858.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov8858.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ov8865.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ov8865.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_pdafcamif.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_pdaf.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ppbase_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ppbase_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_qtech_f3l8yam_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_qtech_f3l8yam_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_qtech_f5670bq_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_qtech_f5670bq_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_qtech_q13853a_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_qtech_q13853a_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k3l8_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k3l8_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k3l8_mono.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k3l8_mono.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k3l8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k3l8.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k3m2xm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k3m2xm.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k3m2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k3m2xx.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k5e8_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k5e8_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_s5k5e8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_s5k5e8.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_stillmore_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_stillmore_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_sunny_8865_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_sunny_8865_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_sunny_q13v06k_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_sunny_q13v06k_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_sunny_q5v41b_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_sunny_q5v41b_eeprom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_thread_services.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_thread_services.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_tintless_algo.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_tintless_bg_pca_algo.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_trueportrait_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_trueportrait_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_tuning_lookup.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_tuning_lookup.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_tuning.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_ubifocus_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_ubifocus_lib.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCcamera_vpu_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCcamera_vpu_module.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCegdhw.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCegdmahw.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCegehw.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCemore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCemore.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCifocus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCifocus.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLC_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLC_interface.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCjpeg.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCmx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCmx_jpegdec.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCmx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCmx_jpegenc_pipe.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCmx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCmx_jpegenc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCqjpeg_codec.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCqjpegdma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCqjpegdma.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromaflash.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromaflash.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_default_preview_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_default_preview_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_default_video_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_default_video_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_hfr_120_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_hfr_120_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_hfr_60_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_hfr_60_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_hfr_90_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_hfr_90_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_zsl_preview_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_zsl_preview_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov13853_q13853a_zsl_video_bu64291gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov13853_q13853a_zsl_video_bu64291gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_a3_default_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_a3_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_a3_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_a3_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_a3_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_ds_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_us_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_video_full.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_video_full.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_zsl_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_ov5670_f5670bq_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_ov5670_f5670bq_zsl_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_a3_default_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_a3_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_a3_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_a3_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_a3_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_ds_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_us_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_video_full.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_video_full.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_zsl_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_plus_ov5670_f5670bq_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_plus_ov5670_f5670bq_zsl_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_default_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_default_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_default_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_default_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_120_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_120_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_60_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_60_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_90_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_90_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_zsl_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_zsl_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_qtech_s5k3l8_f3l8yam_zsl_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_qtech_s5k3l8_f3l8yam_zsl_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_default_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_default_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_default_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_default_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_hfr_120_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_hfr_120_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_hfr_60_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_hfr_60_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_hfr_90_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_hfr_90_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_default_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_default_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_default_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_default_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_120_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_120_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_60_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_60_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_90_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_90_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_zsl_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_zsl_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_new_zsl_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_new_zsl_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_zsl_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_zsl_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k3l8_f3l8yam_zsl_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k3l8_f3l8yam_zsl_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_a3_default_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_a3_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_a3_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_a3_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_a3_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_ds_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_us_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_zsl_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_s5k5e8_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_s5k5e8_zsl_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_a3_default_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_a3_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_a3_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_a3_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_a3_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_ds_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_us_chromatix.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_video_full.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_video_full.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_zsl_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_ov5670_f5670bq_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_ov5670_f5670bq_zsl_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_default_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_default_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_default_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_default_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_120_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_120_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_60_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_60_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_90_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_90_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_common.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_cpp_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_default_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_default_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_default_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_default_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_default_video.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_120_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_120_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_120.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_60_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_60_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_60.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_90_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_90_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_hfr_90.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_liveshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_zsl_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_zsl_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_zsl_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_new_zsl_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_postproc.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_preview.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_snapshot.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_zsl_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_zsl_preview_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCromatix_sunny_s5k3l8_f3l8yam_zsl_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCromatix_sunny_s5k3l8_f3l8yam_zsl_video_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCrpho_easy_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCrpho_easy_hdr.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCrpho_hdr_checker.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCrpho_hdr_checker.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCrpho_image_stab4.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCrpho_image_stab4.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCrpho_panorama_gp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCrpho_panorama_gp.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCtizoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCtizoom.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCtuator_bu64244gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCtuator_bu64244gwz.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCtuator_dw9718s.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCtuator_dw9718s.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCtuator_dw9763_ov13853.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCtuator_dw9763_ov13853.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCtuator_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCtuator_dw9763.so \
    vendor/xiaomi/mi8937/camera/land/vendor/lib/libLCueportrait.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLCueportrait.so
