PRODUCT_COPY_FILES += \
    vendor/xiaomi/mi8937/camera/santoni/vendor/bin/santoni_mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/santoni_mm-qcamera-daemon \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/camera_config.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/csidtg_camera.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/csidtg_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx214_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx214_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx230_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx230_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx230_qc2002_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx230_qc2002_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx230_qc2002_with_gyro_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx230_qc2002_with_gyro_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx258_bear_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx258_bear_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx258_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx258_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx258_mono_bear_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx258_mono_bear_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx258_mono_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx258_mono_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx298_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx298_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx298_gt24c64_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx298_gt24c64_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx318_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx318_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx362_chromatix_bear.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx362_chromatix_bear.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx362_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx362_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/imx378_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/imx378_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov13850_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov13850_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov13850_q13v06k_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov13850_q13v06k_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov13855_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov13855_qtech_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov13855_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov13855_sunny_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov2281_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov2281_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov2680_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov2680_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov4688_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov4688_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov5670_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov5670_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov5675_d5v15b_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov5675_d5v15b_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov5675_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov5675_ofilm_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov5695_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov5695_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov7251_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov7251_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov8858_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov8858_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/ov8865_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/ov8865_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k2l7_8953_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k2l7_8953_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k2l7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k2l7_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3l2_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3l2_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3l8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3l8_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3l8_mono_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3l8_mono_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3l8_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3l8_ofilm_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3l8_ofilm_riva_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3l8_ofilm_riva_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3m2xm_chromatix_bear.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3m2xm_chromatix_bear.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3m2xm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3m2xm_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3m2xx_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3m2xx_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k3p3sm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k3p3sm_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k5e8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k5e8_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k5e8_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k5e8_ofilm_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k5e8_ofilm_riva_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k5e8_ofilm_riva_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k5e8_qtech_riva_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k5e8_qtech_riva_chromatix.xml \
    vendor/xiaomi/mi8937/camera/santoni/vendor/etc/santoni_camera/s5k5e8_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/santoni_camera/s5k5e8_sunny_chromatix.xml
